services:
    HalloVerden\RequestEntityBundle\Interfaces\RequestEntityServiceInterface:
        class: HalloVerden\RequestEntityBundle\Services\RequestEntityService
        arguments:
            $serializer: '@jms_serializer.serializer'
            $dispatcher: '@event_dispatcher'
            $validator: '@validator'

    HalloVerden\RequestEntityBundle\ValueResolvers\RequestEntityResolver:
        arguments:
            $requestEntityService: '@HalloVerden\RequestEntityBundle\Interfaces\RequestEntityServiceInterface'

    HalloVerden\RequestEntityBundle\EventListener\JsonRequestSubscriber:
        tags:
            - { name: 'kernel.event_subscriber' }
